#!/usr/bin/env bash
#
# nut/client/install.sh
#
# Installs or removes NUT client configuration and fallback script.
#

set -euo pipefail
IFS=$'\n\t'

ACTION="${1:---install}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load centralized environment configuration if available
POWERCTL_ENV_FILE="${POWERCTL_ENV_FILE:-/usr/local/powerctl/common/env}"
if [[ -f "$POWERCTL_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$POWERCTL_ENV_FILE"
fi

NUT_CONF_DIR="${NUT_CONF_DIR:-/etc/nut}"
POWERCTL_ROOT="${POWERCTL_ROOT:-/usr/local/powerctl}"
POWERCTL_RUN_DIR="${POWERCTL_RUN_DIR:-/run/powerctl}"
UPSSCHED_BIN="${UPSSCHED_BIN:-/usr/sbin/upssched}"

DRY_RUN=false

log() {
    local level="$1"
    shift
    logger -t nut-client-install -p "user.${level}" -- "$*"
}

info()  { log info  "$*"; }
warn()  { log warn  "$*"; }
error() { log err   "$*"; }

require_root() {
    if [[ "$EUID" -ne 0 ]]; then
        error "This installer must be run as root"
        exit 1
    fi
}

run() {
    if $DRY_RUN; then
        info "[dry-run] $*"
    else
        "$@"
    fi
}

write_file() {
    local path="$1"
    shift
    if $DRY_RUN; then
        info "[dry-run] write $path"
    else
        cat >"$path" <<EOF
$*
EOF
    fi
}

install_all() {
    require_root
    info "Installing NUT client configuration"

    run mkdir -p "$NUT_CONF_DIR" "$POWERCTL_RUN_DIR" "${POWERCTL_ROOT}/nut-client"

    write_file "${NUT_CONF_DIR}/nut.conf" \
"# Generated by nut/client/install.sh
MODE=netclient"

    write_file "${NUT_CONF_DIR}/upsmon.conf" \
"# Generated by nut/client/install.sh
MONITOR ${UPS_NAME:-ups}@${NUT_SERVER_HOST:-127.0.0.1} 1 ${NUT_MON_USER:-monuser} ${NUT_MON_PASS:-change_me} slave

MINSUPPLIES 1
SHUTDOWNCMD \"${SHUTDOWN_CMD:-/sbin/shutdown -h now}\"

POLLFREQ 5
POLLFREQALERT 5
DEADTIME 15

NOTIFYCMD ${UPSSCHED_BIN}
NOTIFYFLAG ONBATT  SYSLOG+EXEC
NOTIFYFLAG ONLINE  SYSLOG+EXEC
NOTIFYFLAG LOWBATT SYSLOG+EXEC
NOTIFYFLAG COMMOK  SYSLOG+EXEC
NOTIFYFLAG COMMBAD SYSLOG+EXEC
NOTIFYFLAG COMMFAULT SYSLOG+EXEC"

    write_file "${NUT_CONF_DIR}/upssched.conf" \
"# Generated by nut/client/install.sh
CMDSCRIPT ${POWERCTL_ROOT}/nut-client/ups_event.sh
PIPEFN ${POWERCTL_RUN_DIR}/upssched.pipe
LOCKFN ${POWERCTL_RUN_DIR}/upssched.lock

# Power loss handling (local fallback)
AT ONBATT   * EXECUTE onbatt
AT ONBATT   * START-TIMER onbatt_shutdown ${NUT_CLIENT_ONBATT_GRACE:-300}
AT ONLINE   * EXECUTE online
AT ONLINE   * CANCEL-TIMER onbatt_shutdown

# Low battery handling (immediate local shutdown)
AT LOWBATT  * EXECUTE lowbatt

# Communication loss with NUT server (fallback shutdown)
AT COMMBAD  * EXECUTE commbad
AT COMMBAD  * START-TIMER commfault_shutdown ${NUT_CLIENT_COMMFAULT_GRACE:-1800}
AT COMMFAULT * EXECUTE commfault
AT COMMFAULT * START-TIMER commfault_shutdown ${NUT_CLIENT_COMMFAULT_GRACE:-1800}
AT COMMOK  * EXECUTE commok
AT COMMOK  * CANCEL-TIMER commfault_shutdown"

    run install -m 0755 "${PROJECT_ROOT}/scripts/ups_event.sh" "${POWERCTL_ROOT}/nut-client/ups_event.sh"

    run systemctl restart nut-monitor || true
    info "NUT client configuration installed"
}

delete_all() {
    require_root
    info "Removing NUT client configuration"
    run rm -f "${NUT_CONF_DIR}/nut.conf" \
       "${NUT_CONF_DIR}/upsmon.conf" \
       "${NUT_CONF_DIR}/upssched.conf"
    run rm -f "${POWERCTL_ROOT}/nut-client/ups_event.sh"
    run systemctl restart nut-monitor || true
}

status() {
    echo "NUT_CONF_DIR: ${NUT_CONF_DIR}"
    systemctl status nut-monitor --no-pager || true
}

case "$ACTION" in
    --install)
        install_all
        ;;
    --delete)
        delete_all
        ;;
    --status)
        status
        ;;
    --dry-run)
        DRY_RUN=true
        install_all
        ;;
    *)
        echo "Usage: $0 [--install|--delete|--status|--dry-run]"
        exit 1
        ;;
esac
