#
# nut.conf (server)
# Global NUT mode configuration
#

# Standalone: local UPS + local clients (upsd + upsmon on same host)
# netserver: dedicated NUT server (upsd on this host, upsmon on clients)
MODE=netserver
