#
# ups.conf (server)
# UPS device configuration
#

# Synology NAS can see the UPS if the UPS name is "ups".
[ups]
  driver       = "usbhid-ups"
  desc         = "APC Back-UPS Pro BR900MI"
  port         = "auto"
  vendor       = "American Power Conversion"
  product      = "Back-UPS RS  900MI FW:948.g4 .I USB FW:g4"
  serial       = "0B2429L37086"
  vendorid     = "051D"
  productid    = "0002"
  lowbatt      = 20
  offdelay     = 20
  ondelay      = 60

# Example alternative UPS profile (commented)
#[powercom]
#driver       = powercom
#manufacturer = Powercom
#modelname    = BNT-1000ap
#desc         = "Powercom BNT-1000ap"
#serialnumber = 20014201003
#type         = BNT-other
#port         = /dev/powercom
#nobt
