RUN_AS_USER root

MONITOR ups@localhost 1 local-upsmon ups-apc primary

# Give the number of power supplies that must be receiving power to keep
# this system running. Most systems have one power supply.
MINSUPPLIES 1

# Polling frequency for normal activities, measured in seconds.
POLLFREQ 15

# Polling frequency in seconds while UPS on battery.
POLLFREQALERT 5

# How long upsmon will wait before giving up on another upsmon.
HOSTSYNC 15

# Interval to wait before declaring a stale ups "dead".
DEADTIME 120

# Flag file for forcing UPS shutdown on the primary system.
POWERDOWNFLAG /etc/killpower

# Replace battery warning time in seconds.
RBWARNTIME 7200

# No communications warning time in seconds.
NOCOMMWARNTIME 300

# Last sleep interval before shutting down the system.
FINALDELAY 10

# Command to run when the system needs to be brought down.
SHUTDOWNCMD "/sbin/shutdown -h now"

# upsmon calls this to send messages when things happen.
NOTIFYCMD /usr/sbin/upssched

# Custom notification messages.
NOTIFYMSG ONLINE        "UPS %s on line power"
NOTIFYMSG ONBATT        "UPS %s on battery"
NOTIFYMSG LOWBATT       "UPS %s battery is low"
NOTIFYMSG FSD           "UPS %s: forced shutdown in progress"
NOTIFYMSG COMMOK        "Communications with UPS %s established"
NOTIFYMSG COMMBAD       "Communications with UPS %s lost"
NOTIFYMSG COMMFAULT     "Communications with UPS %s failed"
NOTIFYMSG SHUTDOWN      "Auto logout and shutdown proceeding"
NOTIFYMSG REPLBATT      "UPS %s battery needs to be replaced"
NOTIFYMSG NOCOMM        "UPS %s is unavailable"
NOTIFYMSG NOPARENT      "upsmon parent process died - shutdown impossible"

# Notification actions.
NOTIFYFLAG ONLINE       SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT       SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT      SYSLOG+WALL+EXEC
NOTIFYFLAG FSD          SYSLOG+WALL
NOTIFYFLAG COMMOK       SYSLOG+EXEC
NOTIFYFLAG COMMBAD      SYSLOG+EXEC
NOTIFYFLAG COMMFAULT    SYSLOG+EXEC
NOTIFYFLAG SHUTDOWN     SYSLOG+WALL+EXEC
NOTIFYFLAG REPLBATT     SYSLOG+WALL
NOTIFYFLAG NOCOMM       SYSLOG+WALL
NOTIFYFLAG NOPARENT     SYSLOG+WALL
