CMDSCRIPT /etc/nut/bash-scr/ups_event.sh
PIPEFN /etc/nut/upssched/upssched.pipe
LOCKFN /etc/nut/upssched/upssched.lock

# UPS power events mapped to the supervisor state writer
AT ONBATT  * EXECUTE onbatt
AT ONLINE  * EXECUTE online
AT LOWBATT * EXECUTE lowbatt
AT COMMBAD * EXECUTE commbad
AT COMMFAULT * EXECUTE commfault
AT COMMOK * EXECUTE commok