#!/usr/bin/env bash
#
# nut/server/install.sh
#
# Installs or removes NUT server configuration.
# This script is idempotent and uses env configuration.
#

set -euo pipefail
IFS=$'\n\t'

ACTION="${1:---install}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load centralized environment configuration if available
POWERCTL_ENV_FILE="${POWERCTL_ENV_FILE:-/usr/local/powerctl/common/env}"
if [[ -f "$POWERCTL_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$POWERCTL_ENV_FILE"
fi

NUT_CONF_DIR="${NUT_CONF_DIR:-/etc/nut}"
POWERCTL_ROOT="${POWERCTL_ROOT:-/usr/local/powerctl}"
POWERCTL_RUN_DIR="${POWERCTL_RUN_DIR:-/run/powerctl}"
UPSSCHED_BIN="${UPSSCHED_BIN:-/usr/sbin/upssched}"

DRY_RUN=false

log() {
    local level="$1"
    shift
    logger -t nut-server-install -p "user.${level}" -- "$*"
}

info()  { log info  "$*"; }
warn()  { log warn  "$*"; }
error() { log err   "$*"; }

require_root() {
    if [[ "$EUID" -ne 0 ]]; then
        error "This installer must be run as root"
        exit 1
    fi
}

run() {
    if $DRY_RUN; then
        info "[dry-run] $*"
    else
        "$@"
    fi
}

write_file() {
    local path="$1"
    shift
    if $DRY_RUN; then
        info "[dry-run] write $path"
    else
        cat >"$path" <<EOF
$*
EOF
    fi
}

install_all() {
    require_root
    info "Installing NUT server configuration"

    run mkdir -p "$NUT_CONF_DIR" "$POWERCTL_RUN_DIR"

    write_file "${NUT_CONF_DIR}/nut.conf" \
"# Generated by nut/server/install.sh
MODE=netserver"

    write_file "${NUT_CONF_DIR}/ups.conf" \
"# Generated by nut/server/install.sh
[${UPS_NAME:-ups}]
  driver = ${UPS_DRIVER:-usbhid-ups}
  port = ${UPS_PORT:-auto}
  desc = \"${UPS_DESC:-APC UPS}\"
  offdelay = ${UPS_OFFDELAY:-60}"

    write_file "${NUT_CONF_DIR}/upsd.conf" \
"# Generated by nut/server/install.sh
LISTEN ${NUT_SERVER_LISTEN_IP:-127.0.0.1} ${NUT_SERVER_LISTEN_PORT:-3493}
MAXAGE 25"

    write_file "${NUT_CONF_DIR}/upsd.users" \
"# Generated by nut/server/install.sh
[${NUT_MON_USER:-monuser}]
  password = ${NUT_MON_PASS:-change_me}
  upsmon master

[${NUT_ADMIN_USER:-admin}]
  password = ${NUT_ADMIN_PASS:-change_me}
  actions = SET
  instcmds = ALL"

    run chmod 640 "${NUT_CONF_DIR}/upsd.users"

    write_file "${NUT_CONF_DIR}/upsmon.conf" \
"# Generated by nut/server/install.sh
MONITOR ${UPS_NAME:-ups}@localhost 1 ${NUT_MON_USER:-monuser} ${NUT_MON_PASS:-change_me} master

MINSUPPLIES 1
SHUTDOWNCMD \"${SHUTDOWN_CMD:-/sbin/shutdown -h now}\"

POLLFREQ 5
POLLFREQALERT 5
DEADTIME 15

NOTIFYCMD ${UPSSCHED_BIN}
NOTIFYFLAG ONBATT  SYSLOG+EXEC
NOTIFYFLAG ONLINE  SYSLOG+EXEC
NOTIFYFLAG LOWBATT SYSLOG+EXEC
NOTIFYFLAG COMMOK  SYSLOG+EXEC
NOTIFYFLAG COMMBAD SYSLOG+EXEC
NOTIFYFLAG COMMFAULT SYSLOG+EXEC"

    write_file "${NUT_CONF_DIR}/upssched.conf" \
"# Generated by nut/server/install.sh
CMDSCRIPT ${POWERCTL_ROOT}/bin/ups-event-writer.sh
PIPEFN ${POWERCTL_RUN_DIR}/upssched.pipe
LOCKFN ${POWERCTL_RUN_DIR}/upssched.lock

AT ONBATT  * EXECUTE onbatt
AT ONLINE  * EXECUTE online
AT LOWBATT * EXECUTE lowbatt
AT COMMBAD * EXECUTE commbad
AT COMMFAULT * EXECUTE commfault
AT COMMOK * EXECUTE commok"

    run systemctl restart nut-server || true
    run systemctl restart nut-monitor || true
    info "NUT server configuration installed"
}

delete_all() {
    require_root
    info "Removing NUT server configuration"
    run rm -f "${NUT_CONF_DIR}/nut.conf" \
       "${NUT_CONF_DIR}/ups.conf" \
       "${NUT_CONF_DIR}/upsd.conf" \
       "${NUT_CONF_DIR}/upsd.users" \
       "${NUT_CONF_DIR}/upsmon.conf" \
       "${NUT_CONF_DIR}/upssched.conf"
    run systemctl restart nut-server || true
    run systemctl restart nut-monitor || true
}

status() {
    echo "NUT_CONF_DIR: ${NUT_CONF_DIR}"
    systemctl status nut-server --no-pager || true
    systemctl status nut-monitor --no-pager || true
}

case "$ACTION" in
    --install)
        install_all
        ;;
    --delete)
        delete_all
        ;;
    --status)
        status
        ;;
    --dry-run)
        DRY_RUN=true
        install_all
        ;;
    *)
        echo "Usage: $0 [--install|--delete|--status|--dry-run]"
        exit 1
        ;;
esac
