CMDSCRIPT /usr/local/powerctl/bin/ups-event-writer.sh
PIPEFN /run/powerctl/upssched.pipe
LOCKFN /run/powerctl/upssched.lock

AT ONBATT  * EXECUTE onbatt
AT ONLINE  * EXECUTE online
AT LOWBATT * EXECUTE lowbatt
